from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
options=webdriver.ChromeOptions()
options.add_experimental_option("detach",True)
driver=webdriver.Chrome(options=options)
driver.maximize_window()
driver.get("https://demowebshop.tricentis.com/")
sleep(2)
polls=driver.find_elements(By.XPATH, "//a[@target='_blank']")
for poll in polls:
    poll.click()
    sleep(2)
    
# driver.find_element(By.XPATH,'//a[contains(text(),"Gift Cards")]').click()
# sleep(2)
# driver.find_element(By.XPATH,'//a[contains(text(),"$25 Virtual Gift Card")]').click()
# sleep(2)
# driver.find_element(By.XPATH,'//input[@class="recipient-name"]').send_keys('gift_card')
# sleep(1)
# driver.find_element(By.XPATH,'//input[@class="recipient-email"]').send_keys('rajat123@gmail.com')
# sleep(1)
# driver.find_element(By.XPATH,'//input[@class="sender-name"]').send_keys('Rajat Singh')
# sleep(1)
# driver.find_element(By.XPATH,'//input[@class="sender-email"]').send_keys('raja123@gmail.com')
# sleep(1)
# driver.find_element(By.XPATH,'//textarea[@class="message"]').send_keys('gift is add sucessfuly')
# qty=driver.find_element(By.XPATH,'//input[@value="1"]/../../div/input[1]')
# qty.clear()
# qty.send_keys(2)
# driver.find_element(By.XPATH,'//input[@class="button-1 add-to-cart-button"]').click()
# sleep(1)
# driver.find_element(By.XPATH,'(//input[@value="Add to cart"])[1]').click()
# sleep(1)
# driver.find_element(By.CLASS_NAME,"cart-label").click()
# sleep(1)
