from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
driver=webdriver.Chrome()
driver.maximize_window()
driver.get("https://demowebshop.tricentis.com/")
sleep(2)
driver.find_element(By.XPATH,"//a[contains(text(),'Digital downloads')]").click()
sleep(2)
driver.find_element(By.XPATH,"(//input[@value='Add to cart'])[1]").click()
sleep(2)
driver.find_element(By.XPATH,"(//input[@value='Add to cart'])[2]").click()
sleep(2)
driver.find_element(By.XPATH,"(//input[@value='Add to cart'])[3]").click()
sleep(2)
driver.find_element(By.XPATH, "//a[text()='Shopping cart']").click()
sleep(2)
driver.find_element(By.XPATH,"//input[@name='removefromcart']").click()
sleep(2)
driver.find_element(By.XPATH,"(//input[@name='removefromcart'])[2]").click()
sleep(2)
driver.find_element(By.XPATH,"(//input[@name='removefromcart'])[3]").click()
sleep(2)
driver.find_element(By.XPATH,"//input[@name='updatecart']").click()
sleep(4)
driver.close()